#include <stdio.h>

/* vector.c

   This program generates vectors.S, the trap/interrupt entry points.
   Usage: vectors > vectors.S

   by Hiroshi Uno */

int main (int argc, char *argv[])
{
	int	i;

	printf ("# generated by vectors.pl - do not edit\n");
	printf ("# handlers\n");
	printf (".globl alltraps\n");
	for(i = 0; i < 256; i++){
    	printf (".globl vector%d\n", i);
    	printf ("vector%d:\n", i);
    	if(!(i == 8 || (i >= 10 && i <= 14) || i == 17)){
        	printf ("  pushl $0\n");
    	}
    	printf ("  pushl $%d\n", i);
    	printf ("  jmp alltraps\n");
	}

	printf ("\n# vector table\n");
	printf (".data\n");
	printf (".globl vectors\n");
	printf ("vectors:\n");
	for(i = 0; i < 256; i++){
    	printf ("  .long vector%d\n", i);
	}
}

/*
 sample output:
   ## handlers
   .globl alltraps
   .globl vector0
   vector0:
     pushl $0
     pushl $0
     jmp alltraps
   ...
   
   ## vector table
   .data
   .globl vectors
   vectors:
     .long vector0
     .long vector1
     .long vector2
   ...
*/
